spring:
  application:
    name: Poj_1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/vue?serverTimezone=GMT%2b8
    username: root
    password: 123
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8081
# \u81EA\u5B9A\u4E49\u5C5E\u6027
ip: localhost
